#brew "fzf"
brew "gh"
brew "jq"
brew "neovim"
#brew "ripgrep"
brew "tmux"
brew "tree"
brew "volta"

cask "discord"
cask "google-chrome"
cask "iterm2"
cask "monitorcontrol"
cask "ollama"
cask "plex"
cask "raycast"
cask "spotify"
cask "visual-studio-code"