if ENV["CODESPACES"]
  cask "claude-code"
elsif RUBY_PLATFORM =~ /darwin/
  brew "fzf"
  brew "gh"
  brew "jq"
  brew "lazydocker"
  brew "lazygit"
  brew "neovim"
  brew "podman"
  brew "python@3.11"
  brew "tmux"
  brew "tree"
  brew "zoxide"
  # Brew volta doesn't work well...it's installed in the install.sh script instead
  # brew "volta"
  
  cask "1password"
  cask "claude-code"
  cask "cursor"
  cask "discord"
  cask "ghostty"
  cask "google-chrome"
  cask "monitorcontrol"
  cask "plex"
  cask "raycast"
  cask "spotify"
  cask "visual-studio-code"
end